language: python

python:
  - 3.8

install:
  - pip install -r requirements.txt
  - pip install black
  - pip install flake8
  - pip install coverage
  - pip install coveralls

before_script:
  - python manage.py makemigrations
  - python manage.py migrate

script:
  - python -m black . --check
  - python -m flake8 . --ignore=E501,F401 --max-line-length=90
  - python -m coverage run --source='.' manage.py test

after_script:
  - coveralls

after_success:
  coveralls
