language: python

python:
  - 3.8

install:
  - cd backend 
  - pip install -r requirements.txt
  - cd frontend
  - npm install
  - nvm install 16.18.0
  - REACT_APP_GOOGLE_MAPS_API_KEY='$REACT_APP_GOOGLE_MAPS_API_KEY' npm run build
  - cd ..

before_script:
  - python manage.py migrate

script:
  - python -m black . --check
  - python -m flake8 . --ignore=W605,F841,W503
  - python -m coverage run --source='NycBasics' manage.py test

after_script:
  - coveralls

after_success:
  coveralls

deploy:
  - provider: elasticbeanstalk
    access_key_id: $ACCESSKEYID
    secret_access_key: $SECRETACCESSKEY
    region: 'us-west-2'
    app: 'NYC-Basics'
    env: 'NYCbasics-staging'
    bucket_name: 'elasticbeanstalk-us-west-2-travis'
    on:
      branch: develop

  - provider: elasticbeanstalk
    access_key_id: $ACCESSKEYID
    secret_access_key: $SECRETACCESSKEY
    region: 'us-west-2'
    app: 'NYC-Basics'
    env: 'NYCbasics-prod'
    bucket_name: 'elasticbeanstalk-us-west-2-travis'
    on:
      branch: master
