language: python

python:
  - 3.8

env: 
  CI: false

install:
  - cd backend 
  - pip install -r requirements.txt

script:
  - python -m black . --check
  - python -m flake8 . --ignore=W605
  - python -m coverage run manage.py test --noinput

after_script:
  - coveralls

after_success:
  coveralls

deploy:

 - provider: elasticbeanstalk
   access_key_id: $NYCBASICSKEY
   secret_access_key: $NYCBASICSSECRETSKEY
   region: 'us-west-2'
   app: 'nycbasics-staging'
   env: 'nycbasics-staging-env'
   bucket_name: 'travis-staging-bucket'
   on:
     branch: develop

 - provider: elasticbeanstalk
   access_key_id: $NYCACCESSKEYID
   secret_access_key: $NYCSECRETACCESSKEY
   region: 'us-west-2'
   app: 'nycstaging'
   env: 'nycprod-env'
   bucket_name: 'travis-prod-bucket'
   on:
     branch: master


