branch-defaults:
  feature/63-FE-Search-GPS:
    environment: team-5-inperson-apptest
    group_suffix: null
global:
  application_name: team-5-inperson
  branch: null
  default_ec2_keyname: aws-eb8
  default_platform: Python 3.8 running on 64bit Amazon Linux 2
  default_region: us-west-2
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  repository: null
  sc: git
  workspace_type: Application
